### PR TITLE
Mapping - tweaks, additions, GATOfication

### LINKED ISSUE #100: Biodome turbine exhaust destroys windows and damages atmos
### Client Version:

_No response_

### Issue Summary:

Biodome has its Turbine vent exhaust on floor tiles. This causes the gasses to spread to the literal gas trap which has 3 windows. Those windows cannot withstand the hot gasses from the turbine exhaust. This causes them to break and hot gasses to flood into the turbine room and the maints hallway opposite of it.

Image

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

Fire the turbine up on biodome, and open the turbine exhaust blast doors

### PR DESCRIPTION
**Pull request by evilew**
This PR focuses on mapping, whether it's tweaking, fixing, adding or just reflavoring stuff.

The biggest tweaks would be GATOifying two maps (Biodome and Tramstation), tweaked Persistence Hostage to have optional kink elements, added Calorite Temple as a bitrunning mission and some other smaller things

(WIP)

:cl: Evilew
map: updated the Lavaland Persistence Outpost: changed the Prisoner room a bit, adding new options for expansion content, and limiting the role to 2 slots (now with bigger rooms)
add: added a new note to the Syndicate Persistence Hostage, mentioning the newly added expansion content (basically a mention that the role isn't solely focused on expansion content, it caters to both and expansion stuff is optional)
map: added a new Virtual Domain for bitrunning: Calorite Temple. Easy difficulty, provides a few pieces of calorite upon completion (no further mechanics at the moment)
map: cage 4 for Biodome will now feature chocolate slimes instead of cockroaches. Shoddy implementation but should be fine
map: various small tweaks to Meta, Box, Biodome and a few other maps: mostly adding stuff like missing consoles, public autolathes, broken turbine floors on Biodome broken airlocks or making something look better
map: GATOified Biodome map, also improving some of the visuals, like the main Service area, dorms, corridors and whatnot
fix: GATOified Newscasters and console computer screens
map: GATOified Tramstation map
map: New expansion content area for the Ghost Cafe: Evil Feeder Basement
map: Changed and expanded Calorite Temple area in Ghost Cafe
add: added dual-tone jumpsuits for most of the roles into loadouts
fix: added directional calorite windows as a mapping prefab
map: added Xenoarch map. Currently not implemented yet, mostly added so it's there and can be worked on more easily

/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/NtosNewsArchive.jsx [hunk 1]
```diff
@@ -11,7 +12,7 @@ export const NtosNewsArchive = (props) => {
     <NtosWindow width={600} height={800}>
       <NtosWindow.Content scrollable>
         <Section textAlign="center">
-          Archives from the Nanotrasen News Network!
+          Archives from the GATO News Network!
```
Comment (Phantastic-Swan) [inline tgui/packages/tgui/interfaces/NtosNewsArchive.jsx]: Would it be possible to add a GS13 Edit comment here?

**Review by Phantastic-Swan — APPROVED** [review]
Seems good, no large flaws as far as I can see

File: tgui/packages/tgui/interfaces/NtosNewsArchive.jsx (hunk 1 above)
Comment (evilew) [reply tgui/packages/tgui/interfaces/NtosNewsArchive.jsx]: I can't comment in this file, preferred to keep it clean but I mentioned this in the .txt with our base code changes.
